name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install dependencies    
        run: npm install  --no-audit --no-optional --no-fund
      - name: Lint the code
        run: npm run eslint
      - name: Build the code
        run: npm run build
      - name: Test the code
        run: npm run test
      - name: E2E test the code
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start-test
          wait-on: http://localhost:5000

